<?php
session_start();
include "db.php";

if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
    header("Location: login.php");
    exit();
}

/* ===============================
   FETCH DATA
=================================*/

// Summary
$totalMembers = $conn->query("SELECT COUNT(*) as total FROM users")
->fetch_assoc()['total'];

$premium = $conn->query("SELECT COUNT(*) as total FROM users WHERE role='admin'")
->fetch_assoc()['total'];

$sales = $conn->query("SELECT SUM(total) as total FROM orders")
->fetch_assoc()['total'] ?? 0;

// Recent Members
$members = [];
$result = $conn->query("SELECT fullname, username, role FROM users ORDER BY id DESC");

while($row = $result->fetch_assoc()){
    $members[] = $row;
}

// Monthly Sales
$months = [];
$totals = [];

$monthly = $conn->query("
SELECT MONTH(created_at) as month, SUM(total) as total
FROM orders
GROUP BY MONTH(created_at)
ORDER BY MONTH(created_at)
");

while($row = $monthly->fetch_assoc()){
    $months[] = date("M", mktime(0,0,0,$row['month'],1));
    $totals[] = $row['total'];
}
?>

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Flexcore Professional Report</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<style>
*{
    margin:0;
    padding:0;
    box-sizing:border-box;
    font-family:Arial, sans-serif;
}

body{
    background:#f5f7fa;
    padding:40px;
    color:#1e293b;
}

.report{
    max-width:1100px;
    margin:auto;
    background:white;
    padding:40px;
    border-radius:14px;
    box-shadow:0 10px 30px rgba(0,0,0,0.08);
}

/* Header */
.header{
    display:flex;
    justify-content:space-between;
    align-items:center;
    border-bottom:3px solid #7c3aed;
    padding-bottom:20px;
    margin-bottom:30px;
}

.brand{
    font-size:32px;
    font-weight:900;
    color:#7c3aed;
}

.sub{
    color:#64748b;
    margin-top:5px;
}

/* Cards */
.cards{
    display:grid;
    grid-template-columns:repeat(auto-fit,minmax(220px,1fr));
    gap:18px;
    margin-bottom:30px;
}

.card{
    background:#f8fafc;
    border-left:5px solid #7c3aed;
    padding:20px;
    border-radius:12px;
}

.card h4{
    color:#64748b;
    font-size:14px;
    margin-bottom:8px;
}

.card p{
    font-size:28px;
    font-weight:800;
}

/* Section */
.section-title{
    font-size:20px;
    font-weight:800;
    margin:30px 0 15px;
}

/* Table */
table{
    width:100%;
    border-collapse:collapse;
}

th{
    background:#7c3aed;
    color:white;
    padding:12px;
    text-align:left;
}

td{
    padding:12px;
    border-bottom:1px solid #e2e8f0;
}

tr:nth-child(even){
    background:#f8fafc;
}

/* Buttons */
.actions{
    margin-bottom:25px;
    display:flex;
    gap:10px;
}

button{
    padding:12px 20px;
    border:none;
    border-radius:10px;
    cursor:pointer;
    font-weight:700;
}

.print-btn{
    background:#7c3aed;
    color:white;
}

.close-btn{
    background:#e2e8f0;
}

canvas{
    margin-top:15px;
}

/* Footer */
.footer{
    margin-top:40px;
    text-align:center;
    color:#64748b;
    font-size:13px;
}

/* Print */
@media print{
    body{
        background:white;
        padding:0;
    }

    .report{
        box-shadow:none;
        border-radius:0;
    }

    .actions{
        display:none;
    }
}
</style>
</head>

<body>

<div class="report">

<div class="actions">
    <button class="print-btn" onclick="window.print()">🖨 Print Report</button>
    <button class="close-btn" onclick="window.close()">✖ Close</button>
</div>

<div class="header">
    <div>
        <div class="brand">FLEXCORE</div>
        <div class="sub">Official Admin Analytics Report</div>
    </div>

    <div>
        <strong>Date:</strong><br>
        <?php echo date("F d, Y"); ?><br>
        <?php echo date("h:i A"); ?>
    </div>
</div>

<!-- SUMMARY -->
<div class="cards">

<div class="card">
    <h4>Total Members</h4>
    <p><?php echo $totalMembers; ?></p>
</div>

<div class="card">
    <h4>Premium Users</h4>
    <p><?php echo $premium; ?></p>
</div>

<div class="card">
    <h4>Total Revenue</h4>
    <p>₱<?php echo number_format($sales,2); ?></p>
</div>

<div class="card">
    <h4>Generated By</h4>
    <p>Admin</p>
</div>

</div>

<!-- SALES GRAPH -->
<div class="section-title">Monthly Revenue Analytics</div>

<canvas id="salesChart" height="100"></canvas>

<!-- MEMBERS -->
<div class="section-title">Registered Members</div>

<table>
<tr>
    <th>#</th>
    <th>Full Name</th>
    <th>Username</th>
    <th>Role</th>
</tr>

<?php $i=1; foreach($members as $m): ?>
<tr>
    <td><?php echo $i++; ?></td>
    <td><?php echo $m['fullname']; ?></td>
    <td><?php echo $m['username']; ?></td>
    <td><?php echo ucfirst($m['role']); ?></td>
</tr>
<?php endforeach; ?>

</table>

<div class="footer">
Flexcore Gym Management System © <?php echo date("Y"); ?>
</div>

</div>

<script>
const ctx = document.getElementById('salesChart');

new Chart(ctx,{
    type:'bar',
    data:{
        labels: <?php echo json_encode($months); ?>,
        datasets:[{
            label:'Monthly Sales',
            data: <?php echo json_encode($totals); ?>,
            borderWidth:1,
            borderRadius:8
        }]
    },
    options:{
        responsive:true,
        plugins:{
            legend:{
                display:false
            }
        },
        scales:{
            y:{
                beginAtZero:true
            }
        }
    }
});
</script>

</body>
</html>